### ISSUE TITLE
can you make it with sliderable tab view? 

### ISSUE THREAD

**Issue by jahir07** [DevExchanges/AutoHideActionBar#1]
thanks a lot.. i like it.. 
Can you integrate sliderable tab  with autohideaction bar , webview, scrolling view etc??

**Comment by DevExchanges** [comment]
Hi, Jahir!
Your requirement can be done by this Android-ObservableScrollView libary. It's "ViewPagerTabActivity" or "ViewPagerWithFragmentActivity".
Visit it: https://github.com/ksoichiro/Android-ObservableScrollView/blob/master/samples/src/main/java/com/github/ksoichiro/android/observablescrollview/samples/ViewPagerTabActivity.java
Output will be like this: https://raw.githubusercontent.com/ksoichiro/Android-ObservableScrollView/master/samples/images/demo13.gif
